version: "3"

services:
    tester:
        build: .
        volumes:
#            - "//d/Docencia/_Programación/Corrección Automática Programación/TestingGit/salidas://salidas"
#            - "//d/Docencia/_Programación/Corrección Automática Programación/TestingGit/repositorios.txt://repositorios.txt"
            - ./salidas:/salidas
            - ./repositorios.txt:/repositorios.txt
        environment:
            - OAUTH_TOKEN=351533df68b9148e03f789c300f4ba056f22e29f